#Пример Post-запроса на создание пользователя
POST "http://127.0.0.1:5000/advertisements
User-Agent: rest-client
Content-Type: application/json

{
    "name": "adv.name1",
    "description": "adv.description",
    "author": "adv.author"
}
